spring:
  application:
    name: xk-ai-nocode-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xk_ai_nocode
    username: root
    password: root
server:
  servlet:
    port: 8080
    context-path: /api
# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.xk.xkainocode.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
